<?php

namespace App\classes\OutputClasses\service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-28 at 11:59:32.
 */
class CommentOrganizerTest extends \TestCase
{
    static $testcomments = array(
        array("content" => "Test text 1 ", "questionNumber" => 1, "elementScore" => 6.25, "elementID" => 12, "subtask" => 1),
        array("content" => "Test text 2 ", "questionNumber" => 1, "elementScore" => 6.25, "elementID" => 13, "subtask" => 2),
        array("content" => "Test text 3 ", "questionNumber" => 1, "elementScore" => 6.25, "elementID" => 14, "subtask" => 3),
        array("content" => "Test text 4 ", "questionNumber" => 1, "elementScore" => 6.25, "elementID" => 15, "subtask" => 4),
        array("content" => "Test text 5 ", "questionNumber" => 2, "elementScore" => 6.25, "elementID" => 19, "subtask" => 1),
        array("content" => "Test text 6 ", "questionNumber" => 2, "elementScore" => 6.25, "elementID" => 19, "subtask" => 2),
        array("content" => "Test text 7 ", "questionNumber" => 2, "elementScore" => 6.25, "elementID" => 19, "subtask" => 3)
    );

    static $q1_expectedelements = array(
            array('elementID' => 12, 'elementScore' => 6.25, 'subtask' => 1),
            array('elementID' => 13, 'elementScore' => 6.25, 'subtask' => 2),
            array('elementID' => 14, 'elementScore' => 6.25, 'subtask' => 3),
            array('elementID' => 15, 'elementScore' => 6.25, 'subtask' => 4)
            );
    static $q1_expectedcomments = array(
        array("content" => "Test text 1 ", "questionNumber" => 1, "elementScore" => 6.25, "elementID" => 12, "subtask" => 1),
        array("content" => "Test text 2 ", "questionNumber" => 1, "elementScore" => 6.25, "elementID" => 13, "subtask" => 2),
        array("content" => "Test text 3 ", "questionNumber" => 1, "elementScore" => 6.25, "elementID" => 14, "subtask" => 3),
        array("content" => "Test text 4 ", "questionNumber" => 1, "elementScore" => 6.25, "elementID" => 15, "subtask" => 4)
        );
    static $q1_expectedcontents = array('Test text 1 ', 'Test text 2 ', 'Test text 3 ', 'Test text 4 ');

    /**
     * @var CommentOrganizer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new CommentOrganizer();
        $this->printer = new ICommentPrinterMock();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    /**
     * @covers \App\classes\OutputClasses\service\CommentOrganizer::set_printer
     */
    public function testSet_printer()
    {
        $this->object->set_printer($this->printer);
        $this->assertInstanceOf('\App\classes\OutputClasses\service\ICommentPrinter', $this->object->printer);
    }

    /**
     * @covers \App\classes\OutputClasses\service\CommentOrganizer::load_comment_array
     */
    public function testLoad_comment_array()
    {
        $this->assertAttributeEmpty('comments', $this->object);
        $this->object->load_comment_array(self::$testcomments);
        $this->assertAttributeNotEmpty('comments', $this->object);
        $this->assertEquals(count(self::$testcomments), count($this->object->comments));
    }

    /**
     * @covers \App\classes\OutputClasses\service\CommentOrganizer::set_question_numbers
     */
    public function testSet_question_numbers()
    {
        $this->object->set_question_numbers(self::$testcomments);
        $this->assertEquals(array(1, 2), $this->object->questionNumbers);
        $this->assertArrayHasKey(1, $this->object->sorted_comments, "Sorted_comments key set");
        $this->assertArrayHasKey(2, $this->object->sorted_comments, "Sorted_comments key set");
    }

    /**
     * @covers \App\classes\OutputClasses\service\CommentOrganizer::sort_comments
     */
    public function testSort_comments()
    {
        $test = self::$testcomments;
        shuffle($test);
        $this->object->set_question_numbers($test);
        $this->object->sort_comments();

        foreach ($this->object->sorted_comments as $k => $v) {
            $ix = 1;
            //iterate over the comments in each question number, checking if in correct order
            foreach ($v as $r) {
                $this->assertEquals($k, $r['questionNumber'], "Comment in correct sub array of sorted_comments ");
                $this->assertEquals($ix, $r['subtask']);
                $ix++;
            }
        }
    }

    /**
     * @covers \App\classes\OutputClasses\service\CommentOrganizer::run
     */
    public function testRun()
    {
        $questionnumber = 1;
        $title = 'testTitle';
        //setup
        $this->object->set_printer($this->printer);
        $this->object->load_comment_array(self::$testcomments);
        $this->object->set_question_numbers(self::$testcomments);
        $this->object->sort_comments();
        //tested method
        $this->object->run($questionnumber, $title);
        //tests
        $this->assertEquals(self::$q1_expectedcomments, $this->printer->commentTextParagraphs);
        $this->assertEquals(self::$q1_expectedelements, $this->printer->elements);
//        $this->assertEquals($questionnumber, $this->printer->questionNumber_make_comment_body);
        //$this->assertEquals($questionnumber, $this->printer->questionNumber_make_opening);
        //$this->assertEquals($title, $this->printer->questionTitle);
        //$this->assertTrue($this->printer->closing);
        $this->assertTrue($this->printer->printcomment);
    }

    /**
     * @covers \App\classes\OutputClasses\service\CommentOrganizer::make
     */
    public function testMake()
    {
        $questionnumber = 1;
        $title = 'testTitle';
        //setup
        $this->object->set_printer($this->printer);
        $this->object->load_comment_array(self::$testcomments);
        $this->object->set_question_numbers(self::$testcomments);
        $this->object->sort_comments();
        //tested method
        $this->object->make($questionnumber, $title, self::$q1_expectedcomments, self::$q1_expectedelements);
        //tests
        $this->assertEquals(self::$q1_expectedcomments, $this->printer->commentTextParagraphs, "comment array as expected");
        $this->assertEquals(self::$q1_expectedelements, $this->printer->elements, "element array as expected");
//        $this->assertEquals($questionnumber, $this->printer->questionNumber_make_comment_body);
        //$this->assertEquals($questionnumber, $this->printer->questionNumber_make_opening);
        //$this->assertEquals($title, $this->printer->questionTitle);
        //$this->assertTrue($this->printer->closing);
        $this->assertTrue($this->printer->printcomment);
        $this->assertTrue($this->printer->reset);
    }

}
