<?php

namespace App\classes\OutputClasses\service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-30 at 12:17:23.
 */
class ScoreAveragesServiceTest extends \PHPUnit_Framework_TestCase
{
    public static $element_testdata = array('elementAbbr' => 'testAbbr');
        public static $question_testdata = array('elementAbbr' => 'testAbbr');

    /**
     * @var ScoreAveragesService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new ScoreAveragesService();
//        $this->dataaccess = $this->getMockBuilder('\OutputClasses\dao\OutputDataAccess')->disableOriginalConstructor()->getMock();
//        $this->exam = new \IExamMock();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers OutputClasses\service\ScoreAveragesService::set_data_access
     */
    public function testSet_data_access()
    {
//        $this->object->set_data_access($this->dataaccess);
//        $this->assertInstanceOf('\OutputClasses\dao\OutputDataAccess', $this->object->outputdata);
    }

    /**
     * @covers OutputClasses\service\ScoreAveragesService::get_element_averages
     */
    public function testGet_element_averages()
    {
//        $this->dataaccess->expects($this->once())->method('element_averages')->willReturn(self::$element_testdata);
//        $this->object->outputdata = $this->dataaccess;
//        $this->object->get_element_averages($this->exam);
//        foreach (self::$element_testdata as $k => $v) {
//            $this->assertArrayHasKey($k, $this->object->element_averages);
//            $this->assertEquals($v, $this->object->element_averages[$k]);
//        }
    }

    /**
     * @covers OutputClasses\service\ScoreAveragesService::get_question_averages
     */
    public function testGet_question_averages()
    {
//        $this->dataaccess->expects($this->once())->method('question_averages')->willReturn(self::$question_testdata);
//        $this->object->outputdata = $this->dataaccess;
//        $this->object->get_question_averages($this->exam);
//        foreach (self::$question_testdata as $k => $v) {
//            $this->assertArrayHasKey($k, $this->object->question_averages);
//            $this->assertEquals($v, $this->object->question_averages[$k]);
//        }

    }

}
