<?php

namespace App\classes\OutputClasses\service;

use App\classes\RequestClasses\IRequestMock;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-30 at 10:03:24.
 */
class StudentLoginManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var StudentLoginManager
     */
    protected $object;
    protected $lookup;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StudentLoginManager();
        $this->lookup = new \OutputClasses\dao\ICredentialLookupMock();
        $this->request = new IRequestMock();

        $this->exam = new \Exam();
        $this->pseudoid = new \PseudoID();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        //unset($this->lookup);
        //unset($this->object);
    }

    /**
     * @covers \OutputClasses\service\StudentLoginManager::set_lookup
     */
    public function testSet_lookup()
    {
        $this->object->set_lookup($this->lookup);
        $this->assertAttributeInstanceOf('\OutputClasses\dao\ICredentialLookup', 'lookup', $this->object);
    }

    /**
     * @covers \OutputClasses\service\StudentLoginManager::process_access_token
     */
    public function testProcess_access_token()
    {
        $testtoken = '3ert4fewr';
        $this->object->set_lookup($this->lookup);
        $this->object->process_access_token($testtoken);
        $this->assertEquals('authenticate', $this->lookup->called);
    }

    /**
     * @covers \OutputClasses\service\StudentLoginManager::process_access_token
     * @expectedException \Exception
     */
        public function testProcess_access_token_throws_on_invalid_chars()
        {
        $testtoken = '3ert4fewr&; ---';
        $this->object->set_lookup($this->lookup);
        $this->object->process_access_token($testtoken);
    }

    public function testLogin()
    {
        $this->request->http['access_code'] = '3ert4fewr';
        $this->request->http['lookup'] = 'testlook';
        $this->lookup->success = true;
        $this->object->set_lookup($this->lookup);

        $result = $this->object->login($this->request);
        $this->assertInstanceOf('\OutputClasses\facades\Visitor', $result);
        $this->assertAttributeInstanceOf('\Exam', 'exam', $result);
        $this->assertAttributeInstanceOf('\Student', 'student', $result);
    }

//    /**
//     * @covers App\classes\StudentClasses\service\StudentLoginManager::get_credentials
//     */
//    public function testGet_credentials()
//    {
//        $this->object->set_lookup($this->lookup, $this->dataservice);
//        $secrets = new \DAO\models\SettableSecrets();
//        $this->object->get_credentials($secrets);
//        $this->assertEquals($this->lookup->username(), $this->object->secrets->username());
//    }
//
//    /**
//     * @covers App\classes\StudentClasses\service\StudentLoginManager::create_dataservice
//     */
//    public function testCreate_dataservice()
//    {
//        $this->assertEmpty($this->object->dataservice);
//        $this->object->secrets = $this->secrets;
//        $this->object->create_dataservice($this->student_service_factory);
//        $this->assertNotEmpty($this->object->dataservice);
//    }
//
//    /**
//     * @covers App\classes\StudentClasses\service\StudentLoginManager::make_student
//     */
//    public function testMake_student()
//    {
//        $this->object->dataservice = $this->dataservice;
//        $testsid = 123456789;
//        $student_ds = new \App\classes\StudentClasses\dao\IStudentDataServiceObjectMock();
//        $student_ds->sid = $testsid;
//        $studentfactory = new \App\classes\StudentClasses\factories\StudentSIDFactory();
//        $this->pseudoid->setID(34567778);
//
//        $this->object->make_student($studentfactory, $student_ds, $this->pseudoid);
//        $this->assertInstanceOf('App\classes\StudentClasses\models\Student', $this->object->student);
//        $this->assertEquals($testsid, $this->object->student->displayID());
//
//    }
//
//    /**
//     * @covers App\classes\StudentClasses\service\StudentLoginManager::set_exam
//     */
//    public function testSet_exam()
//    {
//        $this->lookup->examID = 3;
//        $this->object->set_lookup($this->lookup, $this->dataservice);
//        $this->object->set_exam($this->exam);
//        $this->assertEquals(3, $this->object->exam->displayID());
//    }
}
