<?php

namespace DirectOutputClasses\encoders;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-17 at 13:26:29.
 */
class JavascriptVariableEncoderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var JavascriptVariableEncoder
     */
    protected $object;

    /**
     * Array of legit test strings or teststrings where an easy mistake can be remedied
     * with the dirty string as key and expected clean string as value
     * @var array
     */
    static public $teststrings = array(
        "greatString" => "greatString",
        "stringWithNumber13" => "stringWithNumber13",
        "  accidentallyUntrimmedString  " => "accidentallyUntrimmedString",
    );

    /** @var $evilstrings JavascriptVariableEncoderTest Evil strings which should result in nothing being output */
    static public $evilstrings = array("'<script>alert('Attacked');</script>'",
        "string with spaces",
        "<h1>String with <span class='unwanted'>unwanted </span> html tags</h1>");

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new JavascriptVariableEncoder();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DirectOutputClasses\encoders\JavascriptVariableEncoder::encode_number
     */
    public function testEncode_number()
    {
        $expected = "var TEST = 45; ";
        $php_variable = 45;
        $this->expectOutputString($expected);
        $this->object->encode_number($php_variable, 'TEST');
    }

    /**
     * @covers DirectOutputClasses\encoders\JavascriptVariableEncoder::encode_number
     */
    public function testEncode_numberFloat()
    {
        $expected = "var TEST = 4.5; ";
        $php_variable = 4.5;
        $this->expectOutputString($expected);
        $this->object->encode_number($php_variable, 'TEST');
    }

//    public function testSanitize_number() {
//        $php_variable = '4.5';
//        $result = $this->object->sanitize_number($php_variable);
//        $this->assertEquals(4.5, $result);
//    }

    /**
     * @covers DirectOutputClasses\encoders\JavascriptVariableEncoder::encode_number
     */
    public function testEncode_numberStringInt()
    {
        $expected = "var TEST = 45; ";
        $php_variable = '45';
        $this->expectOutputString($expected);
        $this->object->encode_number($php_variable, 'TEST');
    }

    /**
     * @covers DirectOutputClasses\encoders\JavascriptVariableEncoder::encode_number
     */
    public function testEncode_numberStringFloat()
    {
        $expected = "var TEST = 4.5; ";
        $php_variable = '4.5';
        $this->expectOutputString($expected);
        $this->object->encode_number($php_variable, 'TEST');
    }

    /**
     * @covers DirectOutputClasses\encoders\JavascriptVariableEncoder::encode_string
     */
    public function testEncode_string()
    {
        $expected = "var TEST = 'catfood'; ";
        $php_variable = 'catfood';
        $this->expectOutputString($expected);
        $this->object->encode_string($php_variable, 'TEST');
    }

    /**
     * @covers DirectOutputClasses\encoders\JavascriptVariableEncoder::sanitize_js_name
     */
    public function testSanitize_js_name()
    {
        foreach (self::$teststrings as $input => $clean) {
            $this->assertEquals($clean, $this->object->sanitize_js_name($input));
        }
        foreach (self::$evilstrings as $input) {
            $this->assertFalse($this->object->sanitize_js_name($input));
        }
    }

    /**
     * @covers DirectOutputClasses\encoders\JavascriptVariableEncoder::javascript_tag_open
     */
    public function testJavascript_tag_open()
    {
        $this->expectOutputString('<script type="text/javascript">');
        $this->object->javascript_tag_open();
    }

    /**
     * @covers DirectOutputClasses\encoders\JavascriptVariableEncoder::javascript_tag_close
     */
    public function testJavascript_tag_close()
    {
        $this->expectOutputString("</script>");
        $this->object->javascript_tag_close();
    }

}
