<?php

namespace JsonOutputClasses\controllers;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-11 at 12:55:07.
 */
class ResponseChooserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ResponseChooser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ResponseChooser();
        $this->messagetext = 'message text';
        $this->status_eliciter = array(\JsonOutputClasses\controllers\ResponseChooser::STATUSFLAG => 45);
        $this->status_and_message = array(\JsonOutputClasses\controllers\ResponseChooser::STATUSFLAG => 45,
            \JsonOutputClasses\controllers\ResponseChooser::MESSAGEFLAG => $this->messagetext);
        $this->data_eliciter = array('dummy' => 45);
        //  $this->mockSender = $this->getMockForAbstractClass('\UtilityClasses\JsonOutput\encoders\IJsonOutput');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

//    /**
//     * @covers \JsonOutputClasses\controllers\ResponseChooser::handle_response
//     * @runInSeparateProcess
//     * @preserveGlobalState disabled
//     */
//    public function testHandle_response()
//    {
////        $this->expectOutputString('{"data":[{"dummy":"45"}]}');
//        $this->object->handle_response($this->data_eliciter);
//        $this->assertAttributeInstanceOf('\JsonOutputClasses\encoders\SendDataJson', 'handler', $this->object);
//    }

    /**
     * @covers \JsonOutputClasses\controllers\ResponseChooser::handle_response
     * @expectedException \Exception
     */
    public function testHandle_responseThrowsOnEmptyIncomingArray()
    {
        $this->object->handle_response(array());
    }

    /**
     * @covers \JsonOutputClasses\controllers\ResponseChooser::choose_type
     */
    public function testChoose_type()
    {
        $this->assertEquals('status', $this->object->choose_type($this->status_eliciter));
        $this->assertEquals('status', $this->object->choose_type($this->status_and_message));
        $this->assertEquals('data', $this->object->choose_type($this->data_eliciter));
    }

    /**
     * @covers \JsonOutputClasses\controllers\ResponseChooser::load_appropriate_handler
     */
    public function testLoad_appropriate_handler()
    {
        $this->assertInstanceOf('\JsonOutputClasses\encoders\SendStatusJson', $this->object->load_appropriate_handler('status'));
        $this->assertInstanceOf('\JsonOutputClasses\encoders\SendDataJson', $this->object->load_appropriate_handler('data'));
    }

    /**
     * @covers \JsonOutputClasses\controllers\ResponseChooser::load_appropriate_handler
     * @expectedException \Exception
     */
    public function testLoad_appropriate_handlerExceptsOnInvalidType()
    {
        $this->object->load_appropriate_handler('housecat');
    }

}
