<?php

namespace UserManagement\maker;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-11 at 18:18:44.
 */
class CredentialGeneratorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var CredentialGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CredentialGenerator();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers UserManagement\maker\CredentialGenerator::make_username
     * @covers UserManagement\maker\CredentialGenerator::generate
     */
    public function testMake_username()
    {
        $un = $this->object->make_username();
        $length = strlen($un);
        $this->assertEquals(CredentialGenerator::USERNAME_LENGTH, $length);
    }

    /**
     * @covers UserManagement\maker\CredentialGenerator::make_password
     * @covers UserManagement\maker\CredentialGenerator::generate
     */
    public function testMake_password()
    {
        $pass = $this->object->make_password();
        $length = strlen($pass);
        $this->assertEquals(CredentialGenerator::PASSWORD_LENGTH, $length);
    }

    /**
     * @covers UserManagement\maker\CredentialGenerator::make_db_name
     */
    public function testMake_db_name()
    {
        $teststring = 'test24';
        $expected = CredentialGenerator::DB_NAME_PREFIX . $teststring;
        $result = $this->object->make_db_name($teststring);
        $this->assertEquals($expected, $result);
    }

}
