<?php

namespace JsonOutputClasses\encoders;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-11 at 13:22:57.
 */
class SendDataJsonTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SendDataJson
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SendDataJson();
        $this->testresult = array('catfood' => 'delicious', 'dogfood' => 'abhorrent');
//        $this->testresult = array(array('catfood' => 'delicious', 'dogfood' => 'abhorrent'),
//            array("peoplefood" => "best when stolen", "rat"=>"best served warm"));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

//    public function testEncode_and_send(){
//        $this->assertTrue(true);
//    }
    /**
     * @group slowTests
     * @covers \JsonOutputClasses\encoders\SendDataJson::encode_and_send
     * @covers \JsonOutputClasses\encoders\SendDataJson::package
     * @runInSeparateProcess
     * @preserveGlobalState disabled
     */
    public function testEncode_and_send()
    {
        $ex = '{"data":{"catfood":"delicious","dogfood":"abhorrent"}}';
//        $ex = '{"data":[{"catfood":"delicious", "dogfood":"abhorrent"}, {"peoplefood":"best when stolen", "rat":"best served warm"}]}';
        $this->expectOutputString($ex);
        $this->object->encode_and_send($this->testresult);

    }

}
