<?php

namespace JsonOutputClasses\encoders;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-11 at 14:10:10.
 */
class SendStatusJsonTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SendStatusJson
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SendStatusJson();
        //defining messages here with the constants so will automatically change if ever revise constants or messages
        $this->status_success = \JsonOutputClasses\encoders\SendStatusJson::SUCCESS_STATUS;
        $this->status_fail = \JsonOutputClasses\encoders\SendStatusJson::FAILURE_STATUS;
        $this->msg_success = \JsonOutputClasses\encoders\SendStatusJson::DEFAULT_SUCCESS_MESSAGE;
        $this->msg_fail = \JsonOutputClasses\encoders\SendStatusJson::DEFAULT_FAILURE_MESSAGE;
        $this->statusflag = \JsonOutputClasses\encoders\SendStatusJson::STATUSFLAG;
        $this->messageflag = \JsonOutputClasses\encoders\SendStatusJson::MESSAGEFLAG;
    }

    protected static function getMethod($name)
    {
        $class = new \ReflectionClass('\JsonOutputClasses\encoders\SendStatusJson');
        $method = $class->getMethod($name);
        $method->setAccessible(true);

        return $method;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \JsonOutputClasses\encoders\SendStatusJson::determine_status
     */
    public function testDetermine_status()
    {
        $meth = self::getMethod('determine_status');
        //success case
        $obj = new \JsonOutputClasses\encoders\SendStatusJson();
        $meth->invokeArgs($obj, array(array($this->statusflag => 4)));
        $this->assertAttributeEquals($this->status_success, 'status', $obj);

        //failure case
        $obj2 = new \JsonOutputClasses\encoders\SendStatusJson();
        $meth->invokeArgs($obj2, array(array($this->statusflag => 0)));
        $this->assertAttributeEquals($this->status_fail, 'status', $obj2);
    }

    /**
     * @covers \JsonOutputClasses\encoders\SendStatusJson::determine_message
     */
    public function testDetermine_message()
    {
        $meth = self::getMethod('determine_message');

        $obj = new \JsonOutputClasses\encoders\SendStatusJson();
        $msg = 'custom message';
        $test = array($this->statusflag => 0, $this->messageflag => $msg);
        $meth->invokeArgs($obj, array($test));

        $this->assertAttributeEquals($msg, 'message', $obj);
    }

    /**
     * @covers \JsonOutputClasses\encoders\SendStatusJson::prepare_array
     */
    public function testPrepare_arrayStatusSuccessDefaultMessage()
    {
        $meth = self::getMethod('prepare_array');
        $ex = array('status' => $this->status_success, 'message' => $this->msg_success);
        $this->object->status = $this->status_success;
        $result = $meth->invokeArgs($this->object, array());
        $this->assertEquals($ex, $result);
    }

    /**
     * @covers \JsonOutputClasses\encoders\SendStatusJson::prepare_array
     */
    public function testPrepare_arrayStatusFailDefaultMessage()
    {
        $meth = self::getMethod('prepare_array');
        $ex = array('status' => $this->status_fail, 'message' => $this->msg_fail);
        $this->object->status = $this->status_fail;
        $result = $meth->invokeArgs($this->object, array());
        //$this->object->prepare_array();
        $this->assertEquals($ex, $result);
    }

    /**
     * @covers \JsonOutputClasses\encoders\SendStatusJson::prepare_array
     */
    public function testPrepare_arrayStatusSuccessCustomMessage()
    {
        $meth = self::getMethod('prepare_array');
        $msg = 'custom message';
        $ex = array('status' => $this->status_success, 'message' => $msg);
        $this->object->status = $this->status_success;
        $this->object->message = $msg;
        $result = $meth->invokeArgs($this->object, array());

        $this->assertEquals($ex, $result);
    }

    /**
     * @covers \JsonOutputClasses\encoders\SendStatusJson::prepare_array
     */
    public function testPrepare_arrayWierdStatusDefaultMessage()
    {
        $meth = self::getMethod('prepare_array');
        $status = 'nonStandardStatus';
        $ex = array('status' => $status, 'message' => $this->msg_fail);
        $this->object->status = $status;
        $result = $meth->invokeArgs($this->object, array());
        $this->assertEquals($ex, $result);
    }

    /**
     * @group slowTests
     * @covers \JsonOutputClasses\encoders\SendStatusJson::encode_and_send
     *
     * @runInSeparateProcess
     * @preserveGlobalState disabled
     */
    public function testEncode_and_sendStatusGoodDefaultMessage()
    {
        $test = array($this->statusflag => 4);
        $ex = '{"status":{"status":"' . $this->status_success . '","message":"' . $this->msg_success . '"}}';
        $this->expectOutputString($ex);
        $this->object->encode_and_send($test);
    }

}
