<?php

namespace ScoreClasses\service;

use JsonOutputClasses\encoders\IJsonOutputMock;
use OutputClasses\facades\IVisitorMock;
use ScoreClasses\dao\IScoreDAOMock;
use ScoreClasses\IOutputScoreDAOMock;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-30 at 12:48:58.
 * @todo Revise test data to be more realistic
 */
class StudentScoreServiceTest extends \PHPUnit_Framework_TestCase
{
    static $questions_testdata = array('questionNumber' => 56, 'questionScore' => 5.6);
    static $elements_testdata = array('elementAbbr' => 'TestElementAbbr', 'elementScore' => 5.4);
    static $comments_testdata = array('elementAbbr' => 'TestElementAbbr', 'comment' => 'comment text');
    public $visitor;
    public $data_access;
    public $exam;
    public $student;
    public $question;
    public $element;
    public $encoder;

    /**
     * @var StudentScoreService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $ex = \ExamQuery::create()->findOne();
        $st = \StudentQuery::create()->findOne();

        $this->object = new StudentScoreService();
        $this->encoder = new IJsonOutputMock();
        $this->escores = \ElementScoreQuery::create()->limit(5)->find();
        $this->scores = \QuestionScoreQuery::create()->limit(5)->find();
        $this->object->setEncoder($this->encoder);
        $this->visitor = new IVisitorMock();
        $this->visitor->set_examID($ex->getId());
        $this->visitor->set_studentID($st->getId());
        $this->data_access = new IOutputScoreDAOMock();
        $this->dao = new IScoreDAOMock();
        $this->exam = new \Exam();
        $this->student = new \Student();
        $this->question = new \Question();

        $this->element = new \Element();

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \ScoreClasses\service\StudentScoreService::set_data_access
     */
    public function testSet_data_access()
    {
        $this->object->set_data_access($this->data_access);
        $this->assertInstanceOf('\ScoreClasses\IOutputScoreDAO', $this->object->data_access);
    }

    /**
     * @covers \ScoreClasses\service\StudentScoreService::get_question_scores
     */
    public function testGet_question_scores()
    {
        $this->dao->set_response($this->scores);
        $this->object->set_dao($this->dao);
//        $this->object->set_data_access($this->data_access);
        $this->object->get_question_scores($this->visitor);
        $this->assertInstanceOf('\Exam', $this->exam);
        $this->assertInstanceOf('\Student', $this->student);
//        $this->assertEquals('all_question_scores', $this->data_access->called);
    }

    /**
     * @covers ScoreClasses\service\StudentScoreService::get_particular_question_score
     * @todo   Implement testGet_particular_question_score().
     */
    public function testGet_particular_question_score()
    {
//        $this->data_access->expects($this->once())->method('particular_question_score')->willReturn(self::$questions_testdata);
//        $this->object->data_access = $this->data_access;
//        $this->object->get_particular_question_score($this->exam, $this->student, $this->question);
//        foreach (self::$questions_testdata as $k => $v) {
//            $this->assertArrayHasKey($k, $this->object->question_scores);
//            $this->assertEquals($v, $this->object->question_scores[$k]);
//        }

    }

    /**
     * @covers \ScoreClasses\service\StudentScoreService::get_element_scores
     */
    public function testGet_element_scores()
    {
        $this->dao->set_response($this->escores);
//        $this->object->set_data_access($this->data_access);
        $this->object->set_dao($this->dao);
        $this->object->get_element_scores($this->visitor);
        $this->assertInstanceOf('\Exam', $this->exam);
        $this->assertInstanceOf('\Student', $this->student);
//        $this->assertEquals('all_element_scores', $this->data_access->called);
    }

    /**
     * @covers \ScoreClasses\service\StudentScoreService::get_particular_element_score
     */
    public function testGet_particular_element_score()
    {
//        $this->data_access->expects($this->once())->method('particular_element_score')->willReturn(self::$elements_testdata);
//        $this->object->data_access = $this->data_access;
//        $this->object->get_particular_element_score($this->exam, $this->student, $this->element);
//        foreach (self::$elements_testdata as $k => $v) {
//            $this->assertArrayHasKey($k, $this->object->element_scores);
//            $this->assertEquals($v, $this->object->element_scores[$k]);
//        }
    }

    /**
     * @covers \ScoreClasses\service\StudentScoreService::get_comments
     */
    public function testGet_comments()
    {
//        $this->object->set_dao($this->dao);
////        $this->object->set_data_access($this->data_access);
//        $this->object->get_comments($this->visitor);
//        $this->assertInstanceOf('\Exam', $this->exam);
//        $this->assertInstanceOf('\Student', $this->student);
//        $this->assertEquals('get_comments', $this->data_access->called);
    }

    /**
     * @covers \ScoreClasses\service\StudentScoreService::json_question_scores
     */
    public function testJson_question_scores()
    {

        $this->object->question_scores = self::$questions_testdata;
        $this->object->json_question_scores();
        $this->assertEquals('encode_and_send', $this->encoder->caller);
//        $this->assertJson($this->encoder->args);
    }

    /**
     * @covers \ScoreClasses\service\StudentScoreService::json_element_scores
     */
    public function testJson_element_scores()
    {
        $this->object->element_scores = self::$elements_testdata;
        $this->object->json_element_scores();
        $this->assertEquals('encode_and_send', $this->encoder->caller);
       // $this->assertJson($this->encoder->args);
        //$this->assertJson($this->object->json_element_scores());
    }
    /**
     * @covers \ScoreClasses\service\StudentScoreService::json_comments
     */
    public function testJson_comments()
    {
        $this->object->comments = self::$comments_testdata;
        $this->object->json_comments();
        $this->assertEquals('encode_and_send', $this->encoder->caller);
//        $this->assertJson($this->encoder->args);

//        $this->assertJson($this->object->json_comments());
    }

}
