<?php

namespace App\classes\OutputClasses\display;

use PHPMD\Renderer\HTMLRendererTest;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-04 at 16:38:17.
 */
class QuestionDivMakerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var QuestionDivMaker
     */
    protected $object;
    protected $question;
    protected $element;

    public static $qnum = 5;
    public static $question_title = 'Test Title for 5';

    protected $question_assign;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new QuestionDivMaker();
        $this->question = new \Question();
        $this->question_assign = new \QuestionAssigner();
        $this->element = new \Element();
        $this->element->setId(self::$qnum);
        $this->question->setQuestionname(self::$question_title);
        $this->question_assign->setQuestionnumber(self::$qnum);
        $this->question_assign->setQuestion($this->question);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers OutputClasses\display\QuestionDivMaker::makeOpeningDivTag
     */
    public function testMakeOpeningDivTag()
    {
        $expected = "<div id='q5'>";
        $this->assertEquals($expected, $this->object->makeOpeningDivTag($this->question_assign));
    }

    /**
     * @covers OutputClasses\display\QuestionDivMaker::makeClosingDivTag
     */
    public function testMakeClosingDivTag()
    {
        $this->assertEquals('</div>', $this->object->makeClosingDivTag());
    }

    /**
     * @covers OutputClasses\display\QuestionDivMaker::makeHeading
     */
    public function testMakeHeading()
    {
        $question_number = self::$qnum;
        $question_title = self::$question_title;
        $expected = <<< HTML
<h1 class='mainHeading'>Q{$question_number}: {$question_title}</h1>
<p class='stockText generalStock'></p>
HTML;
        $this->assertEquals($expected, $this->object->makeHeading($this->question_assign));
    }

    /**
     * @covers OutputClasses\display\QuestionDivMaker::makeElementChartDiv
     */
    public function testMakeElementChartDiv()
    {
        $expected = "<div id='el" . self::$qnum . "Chart'></div>";
        $this->assertEquals($expected, $this->object->makeElementChartDiv($this->element));
    }

    /**
     * @covers OutputClasses\display\QuestionDivMaker::makeCommentsArea
     */
    public function testMakeCommentsArea()
    {
        $question_number = self::$qnum;
        $expected = "<ul id='q" . $question_number . "Comments'></ul>";
        $this->assertEquals($expected, $this->object->makeCommentsArea($this->question_assign));
    }

    public function testMakeQuestionChartDiv()
    {
        $question_number = self::$qnum;
        $expected = "<div id='Q" . $question_number . "Chart' "
                . "class='elementChartDiv' "
                . "style='height:" . \OutputClasses\display\QuestionDivMaker::QUESTION_CHART_HEIGHT . "; "
                . "width:" . \OutputClasses\display\QuestionDivMaker::QUESTION_CHART_WIDTH . "' >"
                . " </div>";
        $this->assertEquals($expected, $this->object->makeQuestionChartDiv($this->question_assign));
    }

}
