<?php

namespace App\classes\UserManagement\models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-01 at 19:40:21.
 */
class SettableUserTest extends \TestCase {

    /**
     * @var SettableUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->object = new SettableUser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() {
        
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::check_loaded
     */
    public function testCheck_loaded() {
        $test = 'teststring';
        $this->object->set_db_name($test);
        $this->object->set_db_password($test);
        $this->object->set_db_username($test);
        $this->object->set_ro_password($test);
        $this->object->set_ro_username($test);
        $this->assertTrue($this->object->check_loaded());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::check_loaded
     */
    public function testCheck_loaded_false_if_db_name_unset() {
        $test = 'teststring';
        $this->object->set_db_password($test);
        $this->object->set_db_username($test);
        $this->object->set_ro_password($test);
        $this->object->set_ro_username($test);
        $this->assertFalse($this->object->check_loaded());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::check_loaded
     */
    public function testCheck_loaded_if_db_username_unset() {
        $test = 'teststring';
        $this->object->set_db_name($test);
        $this->object->set_db_password($test);
        $this->object->set_ro_password($test);
        $this->object->set_ro_username($test);
        $this->assertFalse($this->object->check_loaded());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::check_loaded
     */
    public function testCheck_loaded_false_if_db_password_unset() {
        $test = 'teststring';
        $this->object->set_db_name($test);
        $this->object->set_db_username($test);
        $this->object->set_ro_password($test);
        $this->object->set_ro_username($test);
        $this->assertFalse($this->object->check_loaded());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::check_loaded
     */
    public function testCheck_loaded_false_if_ro_password_unset() {
        $test = 'teststring';
        $this->object->set_db_name($test);
        $this->object->set_db_password($test);
        $this->object->set_db_username($test);
        $this->object->set_ro_username($test);
        $this->assertFalse($this->object->check_loaded());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::check_loaded
     */
    public function testCheck_loaded_false_if_ro_username_unset() {
        $test = 'teststring';
        $this->object->set_db_name($test);
        $this->object->set_db_password($test);
        $this->object->set_db_username($test);
        $this->object->set_ro_password($test);
        $this->assertFalse($this->object->check_loaded());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::set_id
     */
    public function testSet_id() {
        $expected = 245;
        $this->object->set_id($expected);
        $this->assertAttributeEquals($expected, 'userID', $this->object);
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::backupDB
     */
    public function testBackupDB() {
        $this->assertTrue($this->object->backupDB());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::displayID
     */
    public function testDisplayID() {
        $expected = 245;
        $this->object->set_id($expected);
        $this->assertAttributeEquals($expected, 'userID', $this->object);
        $this->assertEquals($expected, $this->object->displayID());
    }

//    /**
//     * @covers App\classes\UserManagement\models\SettableUser::display_db_credentials
//     */
//    public function testDisplay_db_credentials() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::set_db_name
     */
    public function testSet_db_name() {
        $expected = 'teststring';
        $this->object->set_db_name($expected);
        $this->assertAttributeEquals($expected, 'db_name', $this->object);
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::get_db_name
     */
    public function testGet_db_name() {
        $expected = 'teststring';
        $this->object->set_db_name($expected);
        $this->assertAttributeEquals($expected, 'db_name', $this->object);
        $this->assertEquals($expected, $this->object->get_db_name());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::set_db_password
     */
    public function testSet_db_password() {
        $expected = 'teststring';
        $this->object->set_db_password($expected);
        $this->assertAttributeEquals($expected, 'db_password', $this->object);
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::get_db_password
     */
    public function testGet_db_password() {
        $expected = 'teststring';
        $this->object->set_db_password($expected);
        $this->assertAttributeEquals($expected, 'db_password', $this->object);
        $this->assertEquals($expected, $this->object->get_db_password());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::set_db_username
     */
    public function testSet_db_username() {
        $expected = 'teststring';
        $this->object->set_db_username($expected);
        $this->assertAttributeEquals($expected, 'db_username', $this->object);
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::get_db_username
     */
    public function testGet_db_username() {
        $expected = 'teststring';
        $this->object->set_db_username($expected);
        $this->assertAttributeEquals($expected, 'db_username', $this->object);
        $this->assertEquals($expected, $this->object->get_db_username());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::get_ro_password
     */
    public function testGet_ro_password() {
        $expected = 'teststring';
        $this->object->set_ro_password($expected);
        $this->assertAttributeEquals($expected, 'ro_password', $this->object);
        $this->assertEquals($expected, $this->object->get_ro_password());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::set_ro_password
     */
    public function testSet_ro_password() {
        $expected = 'teststring';
        $this->object->set_ro_password($expected);
        $this->assertAttributeEquals($expected, 'ro_password', $this->object);
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::set_ro_username
     */
    public function testSet_ro_username() {
        $expected = 'teststring';
        $this->object->set_ro_username($expected);
        $this->assertAttributeEquals($expected, 'ro_username', $this->object);
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::get_ro_username
     */
    public function testGet_ro_username() {
        $expected = 'teststring';
        $this->object->set_ro_username($expected);
        $this->assertAttributeEquals($expected, 'ro_username', $this->object);
        $this->assertEquals($expected, $this->object->get_ro_username());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::isAdmin
     */
    public function testIsAdmin() {
        $this->assertFalse($this->object->isAdmin());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::isReadOnly
     */
    public function testIsReadOnly() {
        $this->assertFalse($this->object->isReadOnly());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::isStudent
     */
    public function testIsStudent() {
        $this->assertFalse($this->object->isStudent());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::isTeacher
     */
    public function testIsTeacher() {
        $this->assertFalse($this->object->isTeacher());
    }

    /**
     * @covers App\classes\UserManagement\models\SettableUser::isTest
     */
    public function testIsTest() {
        $this->assertFalse($this->object->isTest());
    }

}
