<?php

namespace App\classes\DirectOutputClasses\controllers;

use App\classes\DirectOutputClasses\controllers\InternalNavLink;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-25 at 16:13:18.
 */
class InternalNavLinkTest extends \TestCase
{
    /**
     * @var InternalNavLink
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
//        $this->object = new InternalNavLink;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    /**
     * @covers \App\classes\DirectOutputClasses\controllers\InternalNavLink::link
     */
    public function testLink()
    {
        $link = "testpage.php";
        $text = "testpage name";
        $expected = "<a href='$link'>$text</a>";
        $this->expectOutputString($expected);
        InternalNavLink::link($text, $link);

    }

    /**
     * @covers \App\classes\DirectOutputClasses\controllers\InternalNavLink::cleaner
     */
    public function testCleaner()
    {
        $text = "testpage name";
        $result = InternalNavLink::cleaner($text);
        $this->assertEquals($text, $result);
    }

}
