<?php

namespace App\classes\UserManagement\maker;

use App\classes\UserManagement\dao\IDatabaseCreationDaoMock;
use App\classes\UserManagement\dao\IUserTableManagementDaoMock;
use App\classes\UserManagement\errors\NewDbSetupException;
use App\classes\UserManagement\maker\ICredentialGeneratorMock;
use App\classes\UserManagement\maker\ISetupWatcherMock;
use App\classes\UserManagement\maker\SetupWatcher;
use App\classes\UserManagement\models\SettableUser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-22 at 09:33:32.
 */
class AccountSetupTest extends \TestCase {
    public $loadeduser;
    public $user_creation_service;
    public $db_creation_service;
    public $user;

    /**
     * @var AccountSetup
     */
    protected $object;
    public static $dbname = 'gom_testing';
    public static $password = 'testpass';
    public static $username = 'testusername';
    protected $userdao;
    protected $new_db_dao;
    protected $cred_gen;
    protected $watcher;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->object = new AccountSetup();
//        $this->db_dao = new \App\classes\UserManagement\dao\IDatabaseManagementDaoMock();
        $this->userdao = new IUserTableManagementDaoMock();

        $this->watcher = new ISetupWatcherMock();

        $this->cred_gen = new ICredentialGeneratorMock();

        $this->user = new SettableUser();

        $this->new_db_dao = new IDatabaseCreationDaoMock();

//        $this->db_creation_service = new \App\classes\UserManagement\maker\IDatabaseGeneratorMock();
//        $this->user_creation_service = new \App\classes\UserManagement\maker\IUserMakerMock();
        $this->loadeduser = new SettableUser();

        $this->loadeduser->set_id(5);
        $this->loadeduser->set_db_name(self::$dbname);
        $this->loadeduser->set_db_password(self::$password);
        $this->loadeduser->set_db_username(self::$username);
        $this->loadeduser->set_ro_password(self::$password);
        $this->loadeduser->set_ro_username(self::$username);
    }

    public function load() {
        $this->db_creation_service->set_response(true);
        $this->object->set_database_creation_service($this->db_creation_service);

        $user = new SettableUser();
        $user->set_id(2);
        $user->set_db_name(self::$dbname);
        $user->set_db_password(self::$password);
        $user->set_db_username(self::$username);
        $user->set_ro_password(self::$password);
        $user->set_ro_username(self::$username);
        $this->user_creation_service->set_response($user);
//        $this->object->set_user_creation_service($this->user_creation_service);

//        $this->userdao->set_dao(new \DAO\service\UserService());
//        $this->userdao->set_response(true);
//        $this->object->set_user_dao($this->userdao);
//        $this->db_dao->set_response(true);
//        $this->object->set_db_management_dao($this->db_dao);
//        $this->cred_gen->db_name = self::$dbname;
//        $this->cred_gen->password = self::$password;
//        $this->cred_gen->username = self::$username;
//        $this->object->set_credential_generator($this->cred_gen);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() {
    }


    public function testLookupUser()
    {
//        $faker = \Faker\Factory::create();
//        $token = $faker->sha256();
        $token = \Faker\Factory::create()->sha256();
        $userid = 45;
        $this->userdao->set_response($userid);
        $this->object->set_user_table_access($this->userdao);
        $this->object->lookupUser($token);

        $this->assertAttributeNotEmpty('user', $this->object);
        $this->assertAttributeInstanceOf('\App\classes\UserManagement\models\ISettableUser', 'user', $this->object);
        $this->assertEquals('retrieve_userid_from_token', $this->userdao->called);
        $this->assertEquals($token, $this->userdao->called_list[0][1][0]);
    }

    public function testLookupUserExpectedException()
    {
        $this->userdao->throwExceptionOnCall('\App\classes\UserManagement\errors\NewDbSetupException');
        $this->object->set_user_table_access($this->userdao);
        $this->object->setWatcher($this->watcher);
        $this->object->lookupUser(\Faker\Factory::create()->sha256());
        $this->assertTrue($this->watcher->wasCalled);
        $this->assertEquals('handleException', $this->watcher->called);
    }

    /**
     * @expectedException \Exception
     */
    public function testLookupUserUnExpectedException()
    {
        $this->userdao->throwExceptionOnCall('\Exception');
        $this->object->set_user_table_access($this->userdao);
        $this->object->setWatcher($this->watcher);
        $this->object->lookupUser(\Faker\Factory::create()->sha256());
        $this->assertTrue($this->watcher->wasCalled);
        $this->assertEquals('handleException', $this->watcher->called);
    }


    public function testMakeCredentials()
    {
        $user = new SettableUser();
        $user->set_id(2);
        $this->cred_gen->username = self::$username;
        $this->cred_gen->password = self::$password;
        $this->cred_gen->db_name = self::$dbname;
        $this->object->set_credential_generator($this->cred_gen);
        $this->object->user = $user;
        $this->object->setWatcher($this->watcher);

        $this->object->makeCredentials();
        $this->assertEquals(self::$username, $user->get_db_username());
        $this->assertEquals(self::$password, $user->get_db_password());
        $this->assertEquals(self::$username, $user->get_ro_username());
        $this->assertEquals(self::$password, $user->get_ro_password());
        $this->assertEquals(self::$dbname, $user->get_db_name());

        $this->assertEquals('update', $this->watcher->called);
        $this->assertEquals(SetupWatcher::USER_RECORD_FOUND, $this->watcher->called_list[0][1][0]);
    }

    public function testMakeCredentialsExpectedException()
    {
        $user = new SettableUser();
        $this->object->set_credential_generator($this->cred_gen);
        $this->object->user = $user;
        $this->object->setWatcher($this->watcher);

        $this->object->makeCredentials();
        $this->assertEquals(SetupWatcher::USER_RECORD_NOT_FOUND, $this->watcher->called_list[0][1][0]);
        $this->assertTrue($this->watcher->wasCalled);
        $this->assertEquals('handleException', $this->watcher->called);
    }

    /**
     * @expectedException \Exception
     */
    public function testMakeCredentialsUnExpectedException()
    {
        $user = new SettableUser();
        $user->set_id(2);
        $this->cred_gen->throwExceptionOnCall('\Exception');
        $this->object->set_credential_generator($this->cred_gen);
        $this->object->user = $user;
        $this->object->setWatcher($this->watcher);

        $this->object->makeCredentials();
    }
//    /**
//     * @covers App\classes\UserManagement\maker\AccountSetup::set_user_table_access
//     */
//    public function testSet_user_table_access() {
//        $this->object->set_user_table_access($this->userdao);
//        $this->assertAttributeInstanceOf('\App\classes\UserManagement\dao\IUserTableManagementDao', 'user_table_dao', $this->object);
//    }




//    /**
//     * @covers App\classes\UserManagement\maker\AccountSetup::update
//     */
//    public function testUpdate() {
//        $this->object->update(true, "message string");
//        $this->expectOutputString("<p>message string</p>");
//    }
//
//    /**
//     * @covers App\classes\UserManagement\maker\AccountSetup::display_status
//     */
//    public function testDisplay_status() {
//        $this->object->display_status("message string");
//        $this->expectOutputString("<p>message string</p>");
//    }

//    /**
//     * @covers App\classes\UserManagement\maker\AccountSetup::set_database_creation_access
//     */
//    public function testSet_database_creation_access() {
//        $this->object->set_database_creation_access($this->db_creation_service);
//        $this->assertAttributeInstanceOf('\App\classes\UserManagement\maker\IDatabaseCreationService', 'database_creation_service', $this->object);
//    }

    public function testSetWatcher()
    {
        $this->object->setWatcher($this->watcher);
        $this->assertAttributeInstanceOf('\App\classes\UserManagement\maker\ISetupWatcher', 'watcher', $this->object);
    }

    /**
     * @covers App\classes\UserManagement\maker\AccountSetup::set_user_table_service
     */
    public function set_user_table_access() {
        $this->object->set_user_table_access($this->user_creation_service);
        $this->assertAttributeInstanceOf('\App\classes\UserManagement\maker\IUserMaker', 'user_creation_service', $this->object);
    }

    public function testSetNewDbDao()
    {
        $this->object->setNewDbDao($this->new_db_dao);
        $this->assertAttributeInstanceOf('\App\classes\UserManagement\dao\IDatabaseCreationDao', 'new_db_dao', $this->object);
    }


    /**
     * @covers App\classes\UserManagement\maker\AccountSetup::run
     */
    public function testRun()
    {
        $token = \Faker\Factory::create()->sha256();
        $userid = 45;
        $this->userdao->set_response($userid);
        $this->object->set_user_table_access($this->userdao);

        $user = new SettableUser();
        $user->set_id($userid);
        $this->object->user = $user;

        $this->cred_gen->username = self::$username;
        $this->cred_gen->password = self::$password;
        $this->cred_gen->db_name = self::$dbname;
        $this->object->set_credential_generator($this->cred_gen);

        $this->object->setWatcher($this->watcher);

        $this->object->setNewDbDao($this->new_db_dao);

        //action
        $this->object->run($token);

        //assertions not covered in other tests
        $this->assertEquals(SetupWatcher::GOM_USER_COMPLETE, $this->watcher->called_list[2][1][0]);
        $this->assertTrue($this->new_db_dao->wasCalled);
        $this->assertEquals('make', $this->new_db_dao->called);
        $this->assertInstanceOf('\App\classes\UserManagement\models\ISettableUser', $this->new_db_dao->called_list[0][1][0]);

        $result_user = $this->new_db_dao->called_list[0][1][0];
        $this->assertEquals(self::$username, $result_user->get_db_username());
        $this->assertEquals(self::$password, $result_user->get_db_password());
        $this->assertEquals(self::$username, $result_user->get_ro_username());
        $this->assertEquals(self::$password, $result_user->get_ro_password());
        $this->assertEquals(self::$dbname, $result_user->get_db_name());
    }

//    /**
//     * @covers App\classes\UserManagement\maker\AccountSetup::update_db_connection()
//     */
//    public function testUpdate_db_connection() {
////        $this->db_creation_service->set_response(TRUE);
////        $this->object->set_database_creation_service($this->db_creation_service);
////        $this->assertTrue($this->object->update_db_connection($this->loadeduser));
//////        $this->assertAttributeInstanceOf('\DAO\service\UserlessDataService', 'db_creation_dao', $this->object->database_creation_service);
////        $this->assertAttributeInstanceOf('\DAO\service\UserlessDataService', 'db_creation_dao', $this->db_creation_service);
//    }
//
////    /**
////     * @covers App\classes\UserManagement\service\AccountSetup::update_db_connection()
////     * @expectedException \Exception
////     */
////    public function testUpdate_db_connection_throws_exception() {
//////        $this->db_creation_service->set_response(FALSE);
////        $db_creation_service = new \App\classes\UserManagement\service\IDatabaseGenerator();
////        $this->object->set_database_creation_service($db_creation_service);
////        $this->object->update_db_connection($this->user);
////    }
//
//    /**
//     * @covers App\classes\UserManagement\maker\AccountSetup::create_schema()
//     */
//    public function testCreate_schema() {
////        $this->db_creation_service->set_response(TRUE);
////        $this->object->set_database_creation_service($this->db_creation_service);
////        $this->user_creation_service->set_response(TRUE);
////        $this->object->set_user_creation_service($this->user_creation_service);
////        $this->assertTrue($this->object->create_schema($this->loadeduser));
//    }

//    /**
//     * @covers App\classes\UserManagement\service\AccountSetup::create_schema()
//     * @expectedException \Exception
//     */
//    public function testCreate_schema_throws_exception_on_db_creation_fail() {
//        $this->db_creation_service->set_response();
//        $this->object->set_database_creation_service($this->db_creation_service);
//        $this->user_creation_service->set_response(TRUE);
//        $this->object->set_user_creation_service($this->user_creation_service);
//        $this->assertTrue($this->object->create_schema($this->loadeduser));
//    }

//    /**
//     * @covers App\classes\UserManagement\service\AccountSetup::create_schema()
//     * @expectedException \Exception
//     */
//    public function testCreate_schema_throws_exception_on_user_creation_fail() {
//        $this->db_creation_service->set_response(TRUE);
//        $this->object->set_database_creation_service($this->db_creation_service);
//        $this->user_creation_service->set_response();
//        $this->object->set_user_creation_service($this->user_creation_service);
//        $this->assertTrue($this->object->create_schema($this->loadeduser));
//    }
//
//    /**
//     * @covers App\classes\UserManagement\service\DatabaseGenerator::run
//     * @expectedException \Exception
//     */
//    public function testRun_throws_exception_if_dao_response_not_true() {
//        $this->userdao->set_retrieve_userid_response(5);
////        prepare the object which the credentials lookup will return
//        $user = new \App\classes\UserManagement\models\SettableUser();
//        $user->set_id(5);
//        $user->set_db_name(self::$dbname);
////        $user->set_db_password(self::$password);
////        $user->set_db_username(self::$username);
////        $user->set_ro_password(self::$password);
////        $user->set_ro_username(self::$username);
////        $this->userdao->set_retrieve_credentials_response($user);
////        $this->object->set_user_table_service($this->userdao);
//        $this->dao->set_response(FALSE);
//        $this->object->set_dataservice($this->dao);
//        $this->object->run_database_setup($this->loadeduser);
//    }
//
////    /**
////     * @covers App\classes\UserManagement\service\DatabaseGenerator::run_database_setup
////     * @expectedException \Exception
////     */
////    public function testRun_database_setup_throws_exception_if_credentials_do_not_load() {
//////        $this->userdao->set_retrieve_userid_response(5);
////        //prepare the object which the credentials lookup will return
//////        $user = new \App\classes\UserManagement\models\SettableUser();
//////        $user->set_id(5);
//////        $this->userdao->set_retrieve_credentials_response($user);
//////        $this->object->set_user_table_service($this->userdao);
////        $this->dao->set_response(TRUE);
////        $this->object->set_dataservice($this->dao);
////        $this->object->run_database_setup($this->user);
//    }

//    /**
//     * @covers App\classes\UserManagement\service\AccountSetup::redirect
//    //     */
//    public function testRedirect() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
    
    //    /**
//     * @covers App\classes\UserManagement\service\AccountSetup::set_db_management_dao
//     */
//    public function thisSet_db_management_dao() {
//        $this->object->set_db_management_dao($this->db_dao);
//        $this->assertAttributeInstanceOf('\App\classes\UserManagement\dao\IDatabaseManagementDao', 'db_management_dao', $this->object);
//    }
//    /**
//     * @covers App\classes\UserManagement\service\AccountSetup::set_user_dao
//     */
//    public function testSet_user_dao() {
//        $this->object->set_user_dao($this->userdao);
//        $this->assertAttributeInstanceOf('\App\classes\UserManagement\dao\IUserTableManagementDao', 'user_table_dao', $this->object);
//    }
//
//    /**
//     * @covers App\classes\UserManagement\service\AccountSetup::set_credential_generator
//     */
//    public function testSet_credential_generator() {
//        $this->object->set_credential_generator($this->cred_gen);
//        $this->assertAttributeInstanceOf('\App\classes\UserManagement\service\ICredentialGenerator', 'credential_generator', $this->object);
//    }
}
