<?php

namespace App\classes\ScoreClasses;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-11 at 11:43:07.
 */
class OutputElementScoresTest extends \TestCase
{
    /**
     * @var OutputElementScores
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
//        $this->object = new OutputElementScores;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    public function test_load_and_send()
    {
//     load_and_send($exam, $student, $qid);
    }

    public function test_get_questions_for_exam()
    {
//        get_questions_for_exam($exam)
    }

    public function test_get_student_score_and_item_for_question()
    {
//        get_student_score_and_item_for_question($exam, $student, $questionID);
    }

    public function test_build_results_array()
    {
//        build_results_array($question_ids, $student, $exam)
    }

    public function encode_and_send_results()
    {
//        encode_and_send_results($results_array);
    }

}
