<?php

namespace App\classes\DirectOutputClasses\encoders;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-16 at 12:08:25.
 */
class HtmlEncoderTest extends \TestCase
{
    /**
     * @var HtmlEncoder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new HtmlEncoder();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown()
    {
    }

    /**
     * @covers App\classes\DirectOutputClasses\encoders\HtmlEncoder::clean
     */
    public function testClean()
    {
        $test = "<h1>Test string</h1>";
        $result = $this->object->clean($test);
        $this->assertEquals($result, $test);

    }

}
